spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id : messageFeign
        uri : lb://feignClient
        predicates:
        - Method=GET
        - Path=/message/feign
      - id : message
        uri : lb://springClient
        predicates:
        - Method=GET
        - Path=/message
  security:
    oauth2:
      client:
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: uwSgzoTfLniSN6Nijagcr1D35xnbeB8c
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
        provider:
          keycloak:
            issuer-uri: https://193.95.34.27:8443/auth/realms/spring
server:
  port: 8000
